language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq -d update

install:
  - if [ $CC = 'gcc' ]; then sudo apt-get install g++-5; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90; fi
  - if [ $CC = 'clang' ]; then sudo apt-get install clang; fi
  - g++ --version

script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
  - make
